name: Publish image to container registry

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
        docker_image: ${{ steps.vars.outputs.docker_image }}
        build_tag: ${{ steps.vars.outputs.build_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: |
          echo "docker_image=${{ env.REGISTRY}}/${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "build_tag=$(git show -s --format=%h-%cd --date=format:%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.build_tag }}
            ${{ steps.vars.outputs.docker_image }}:latest
