name: Build and publish a specification document

on:
  workflow_call:
    inputs:
      publish:
        description: 'Whether to publish the result'
        type: boolean
        default: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Render .liquid template files
        if: ${{ hashFiles('**/*.liquid') != '' }}
        run: |
          set -e
          for template_file in $(find . -name '*.liquid' -type f); do
            output_file="${template_file%.liquid}"
            npx --yes @lde/docgen@latest from-shacl shacl.ttl "$template_file" > "$output_file"
          done

      - name: Render Mermaid diagrams
        if: ${{ hashFiles('**/*.mmd') != '' }}
        run: |
          set -e
          for mermaid_file in $(find . -name '*.mmd' -type f); do
            output_file="${mermaid_file%.mmd}.svg"
            npx --yes -p @mermaid-js/mermaid-cli mmdc -i "$mermaid_file" -o "$output_file" --backgroundColor transparent --theme neutral
          done

      - name: Build and validate
        uses: w3c/spec-prod@v2
        with:
          VALIDATE_MARKUP: false

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.publish }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: spec-prod-result

      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - uses: actions/configure-pages@v5

      - id: deployment
        uses: actions/deploy-pages@v4
