name: Build and publish a specification document

on:
  workflow_call:
    inputs:
      publish:
        description: 'Whether to publish the result'
        type: boolean
        default: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        if: ${{ hashFiles('index.bs.liquid') != '' }}
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Generate index.bs based on SHACL shapes
        if: ${{ hashFiles('index.bs.liquid') != '' }}
        run: npx --yes @lde/docgen@latest from-shacl shacl.ttl index.bs.liquid > index.bs

      - name: Build and validate
        uses: w3c/spec-prod@v2
        with:
          VALIDATE_MARKUP: false

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.publish }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: spec-prod-result

      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - uses: actions/configure-pages@v5

      - id: deployment
        uses: actions/deploy-pages@v4
